# Generated by Django 4.1.1 on 2022-09-28 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('reviews', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=50, null=True)),
                ('stock', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('1', 'Customer'), ('2', 'Shoper')], default='1', help_text=' User type (Customer, Shoper)', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('alternate_phone', models.BigIntegerField(blank=True, null=True)),
                ('terms_condition_privacy', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=30, null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
